name: Build CI

on:
  push:

jobs:
  frontend:
    name: Frontend Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump Version
        uses: GarnerCorp/build-actions/bump-version@main
        id: version
        with:
          version-type: "node"
          version-file-path: "package.json"
          git-name: "andriy"
          git-email: "andriy@example.com"
          major: changelogs/major
          minor: changelogs/minor

      - name: Build
        run: |
          if [ $GITHUB_RUN_ATTEMPT -eq 1 ]; then
            echo ::warning This is intentionally flakey. Please rerun
            exit 5
          fi
          echo ::notice This is stable
