name: Build CI

on:
  push:

jobs:
  frontend:
    name: Frontend Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump Version
        uses: GarnerCorp/build-actions/bump-version@main
        id: version
        continue-on-error: true
        with:
          version-type: "node"
          version-file-path: "package.json"
          git-name: "andriy"
          git-email: "andriy@example.com"
          major: changelogs/major
          minor: changelogs/minor
      - name: "Something"
        if: steps.version.outcome == 'failure' && github.run_attempt == '1'
        run: |
          echo ::error::This is bad and should not happen
          exit 3
      - name: Build
        run: |
          if [ $GITHUB_RUN_ATTEMPT -eq 1 ]; then
            echo ::warning ::This is intentionally flakey. Please rerun
            exit 5
          fi
          echo ::notice ::This is stable
